version: "3.9"
services:
  pg_test:
    image: postgres:16
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: task_manager_test
    ports:
      - "5433:5432"
